app:
  jwt:
    public_keys_url: classpath:local-development/jwks.json

spring:
  profiles:
    active: "test"
  datasource:
    url: "jdbc:postgresql://localhost:5432/vekkuli_it"
    username: "vekkuli"
    password: "postgres"
