CREATE OR REPLACE FUNCTION public.trigger_refresh_updated() RETURNS trigger
    LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated = NOW();
RETURN NEW;
END;
$$;

ALTER TABLE boat
    ADD COLUMN created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TRIGGER set_timestamp BEFORE UPDATE ON boat
    FOR EACH ROW EXECUTE PROCEDURE trigger_refresh_updated();

ALTER TABLE boat_space
    ADD COLUMN created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TRIGGER set_timestamp BEFORE UPDATE ON boat_space
    FOR EACH ROW EXECUTE PROCEDURE trigger_refresh_updated();

ALTER TABLE citizen
    ADD COLUMN created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TRIGGER set_timestamp BEFORE UPDATE ON citizen
    FOR EACH ROW EXECUTE PROCEDURE trigger_refresh_updated();

ALTER TABLE invoice
    ADD COLUMN created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TRIGGER set_timestamp BEFORE UPDATE ON invoice
    FOR EACH ROW EXECUTE PROCEDURE trigger_refresh_updated();

ALTER TABLE organization
    ADD COLUMN created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TRIGGER set_timestamp BEFORE UPDATE ON organization
    FOR EACH ROW EXECUTE PROCEDURE trigger_refresh_updated();

ALTER TABLE reservation_period
    ADD COLUMN created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TRIGGER set_timestamp BEFORE UPDATE ON reservation_period
    FOR EACH ROW EXECUTE PROCEDURE trigger_refresh_updated();

ALTER TABLE sent_message
    ADD COLUMN updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TRIGGER set_timestamp BEFORE UPDATE ON sent_message
    FOR EACH ROW EXECUTE PROCEDURE trigger_refresh_updated();

ALTER TABLE processed_message
    ADD COLUMN created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TRIGGER set_timestamp BEFORE UPDATE ON processed_message
    FOR EACH ROW EXECUTE PROCEDURE trigger_refresh_updated();