ALTER TYPE case_event_type RENAME VALUE 'DIRECTED_TO_SCHOOL_TUVA' TO 'DIRECTED_TO_YLEISOPPILAITOKSEN_TUVA';
ALTER TYPE case_event_type RENAME VALUE 'DIRECTED_TO_SCHOOL_SPECIAL_EDUCATION_TUVA' TO 'DIRECTED_TO_ERITYISOPPILAITOKSEN_TUVA';
ALTER TYPE case_event_type RENAME VALUE 'DIRECTED_TO_SCHOOL_SPECIAL_EDUCATION_TELMA' TO 'DIRECTED_TO_ERITYISOPPILAITOKSEN_TELMA';

CREATE TYPE case_finished_reason AS ENUM (
    'BEGAN_STUDIES',
    'COMPULSORY_EDUCATION_ENDED',
    'COMPULSORY_EDUCATION_SUSPENDED',
    'COMPULSORY_EDUCATION_SUSPENDED_PERMANENTLY',
    'MOVED_TO_ANOTHER_MUNICIPALITY',
    'MOVED_ABROAD',
    'ERRONEOUS_NOTICE',
    'OTHER'
);

CREATE TYPE school_type AS ENUM (
    'PERUSOPETUKSEEN_VALMISTAVA',
    'AIKUISTEN_PERUSOPETUS',
    'AMMATILLINEN_PERUSTUTKINTO',
    'LUKIO',
    'AIKUISLUKIO',
    'YLEISOPPILAITOKSEN_TUVA',
    'AMMATILLISEN_OPPILAITOKSEN_TUVA',
    'AMMATILLISEN_ERITYISOPPILAITOKSEN_PERUSTUTKINTO',
    'TELMA',
    'KANSANOPISTO',
    'OTHER'
);

ALTER TABLE student_cases ADD COLUMN finished_reason case_finished_reason;
UPDATE student_cases SET finished_reason = 'OTHER' WHERE status = 'FINISHED';
ALTER TABLE student_cases ALTER COLUMN finished_reason DROP DEFAULT;
ALTER TABLE student_cases ADD CONSTRAINT check_finished_reason_null_or_required
    CHECK ( (status = 'FINISHED') = (finished_reason IS NOT NULL) );

ALTER TABLE student_cases ADD COLUMN started_at_school school_type;
ALTER TABLE student_cases ADD CONSTRAINT check_started_at_school_null_or_required
    CHECK ( (finished_reason = 'BEGAN_STUDIES') = (started_at_school IS NOT NULL) );
