CREATE TYPE school_background AS ENUM (
    'PERUSKOULUN_PAATTOTODISTUS',
    'EI_PERUSKOULUN_PAATTOTODISTUSTA',
    'KESKEYTYNEET_TOISEN_ASTEEN_OPINNOT',
    'KESKEYTYNEET_NIVELVAIHEEN_OPINNOT',
    'VSOP_PERUSKOULUSSA',
    'YLEINEN_TUKI_PERUSKOULUSSA',
    'TEHOSTETTU_TUKI_PERUSKOULUSSA',
    'ERITYISEN_TUEN_PAATOS_PERUSKOULUSSA',
    'YKSILOLLISTETTY_OPPIMAARA_AIDINKIELESSA_JA_MATEMATIIKASSA',
    'PERUSOPETUKSEEN_VALMISTAVA_OPISKELU_SUOMESSA',
    'ULKOMAILLA_SUORITETUT_PERUSOPETUSTA_VASTAAVAT_OPINNOT'
);

CREATE TYPE case_background_reason AS ENUM (
    'MOTIVAATION_PUUTE',
    'VAARA_ALAVALINTA',
    'OPPIMISVAIKEUDET',
    'ELAMANHALLINNAN_HAASTEET',
    'POISSAOLOT',
    'TERVEYDELLISET_PERUSTEET',
    'MUUTTO_PAIKKAKUNNALLE',
    'MUUTTO_ULKOMAILLE',
    'MAAHAN_MUUTTANUT_NUORI_ILMAN_OPISKELUPAIKKAA',
    'MUU_SYY'
);

CREATE TYPE not_in_school_reason AS ENUM (
    'KATSOTTU_ERONNEEKSI_OPPILAITOKSESTA',
    'EI_OLE_VASTAANOTTANUT_SAAMAANSA_OPISKELUPAIKKAA',
    'EI_OLE_ALOITTANUT_VASTAANOTTAMASSAAN_OPISKELUPAIKASSA',
    'EI_OLE_HAKEUTUNUT_JATKO_OPINTOIHIN',
    'EI_OPISKELUPAIKKAA_YLEISOPPILAITOKSESSA',
    'EI_OPISKELUPAIKKAA_AMMATILLISESSA_ERITYISOPPILAITOKSESSA',
    'EI_OLE_SAANUT_OPISKELUPAIKKAA_KIELITAIDON_VUOKSI',
    'OPINNOT_ULKOMAILLA'
);

ALTER TABLE student_cases
    ADD COLUMN school_background school_background[] NOT NULL DEFAULT '{}'::school_background[],
    ADD COLUMN case_background_reasons case_background_reason[] NOT NULL DEFAULT '{}'::case_background_reason[],
    ADD COLUMN not_in_school_reason not_in_school_reason;
ALTER TABLE student_cases
    ALTER COLUMN school_background DROP DEFAULT,
    ALTER COLUMN case_background_reasons DROP DEFAULT;
