INSERT INTO email_template (id, subject, body)
VALUES
    ('reservation_renewed_by_employee_confirmed', 'Espoon kaupungin {{placeType}}varauksen jatkaminen', E'Hyvä asiakas,\n\nVaraamasi Espoon kaupungin {{placeType}} on jatkettu uudelle kaudelle.\n\nVuokralainen: {{reserverName}}\n\nVenepaikan nimi {{name}}\nVenepaikan leveys {{width}}\nVenepaikan pituus {{length}}\nVenepaikan varustus {{amenity}}\nVarauksesi on voimassa {{endDate}}.\n\nHallinnoi varauksiasi, veneitäsi ja omia tietojasi helposti osoitteessa https://varaukset.espoo.fi/kuntalainen/omat-tiedot.\n\nVenesatamia koskevat sopimusehdot ja säännöt sekä muuta infoa löydät osoitteesta https://www.espoo.fi/fi/liikunta-ja-luonto/veneily.\n\nTerveisin\nMerelliset ulkoilupalvelut\nvenepaikat@espoo.fi');

UPDATE email_template SET subject='Vahvistus Espoon kaupungin {{placeType}}varauksesta',
                          body = E'Hyvä asiakas,\n\nVeneelle varaamasi {{placeType}} on maksettu ja varaus on vahvistettu.\n\nVuokralainen:\n{{reserverName}}\n\nPaikan tiedot:\nPaikan nimi: {{name}}\nPaikan leveys {{width}}\nPaikan pituus {{length}}\nPaikan varuste/säilytystapa {{amenity}}\n\nVarauksesi on voimassa {{endDate}}.\n\nJos varasit laituripaikan, saat myöhemmin postissa kausitarran ja satamakartan, jossa avainkoodi laiturin portin avaimen teettämistä varten (Otsolahden F-laiturille ei ole porttia). Kausitarra tulee kiinnittää näkyvälle paikalle veneeseen tai jos varasit talvi- tai säilytyspaikan, suojatelttaan, traileriin tai pukkiin.\n\nJos varasit säilytyspaikan Ämmäsmäeltä:\nÄmmäsmäen kulkulätkän noudosta tulee sopia ennakkoon soittamalla numeroon 050 3209 681 arkisin kello 9-13. Kulkulätkä noudetaan Suomenojan satamasta (Hylkeenpyytäjäntie 9) maksukuittia näyttämällä.\n\nHallinnoi varauksiasi, veneitäsi ja omia tietojasi helposti osoitteessa https://varaukset.espoo.fi/kuntalainen/omat-tiedot.\n\nVenesatamia koskevat sopimusehdot ja säännöt sekä muuta infoa löydät osoitteesta https://www.espoo.fi/fi/liikunta-ja-luonto/veneily.\n\nTerveisin\nMerelliset ulkoilupalvelut\nvenepaikat@espoo.fi'
WHERE id = 'reservation_created_by_citizen';

UPDATE email_template SET subject='Espoon kaupungin {{placeType}}varaus',
                          body = E'Hyvä asiakas,\n\nSinulle on varattu espoon kaupungin {{reservationDescription}}.\n\nSinulle on lähetetty lasku osoitteeseen {{invoiceAddress}}. Vahvistaaksesi varauksen, maksa paikka eräpäivään mennessä. Maksamaton paikka irtisanoutuu ja se vapautuu muiden varattavaksi. Maksun saavuttua tilillemme lähetämme sähköpostilla lisätietoa laiturin portin avaimesta sekä kausitarran postitse. Kausitarra tulee kiinnittää näkyvälle paikalle veneeseen, tai jos varasit talvi- tai säilytyspaikan, esim. suojatelttaan, traileriin tai pukkiin.\n\nVuokralainen:\n{{reserverName}}\n\nVenepaikan nimi {{name}}\nVenepaikan leveys {{width}}\nVenepaikan pituus {{length}}\nVenepaikan varustus {{amenity}}\nVarauksesi on voimassa {{endDate}}.\n\nJos varasit laituripaikan, saat myöhemmin postissa kausitarran ja satamakartan, jossa avainkoodi laiturin portin avaimen teettämistä varten (Otsolahden F-laiturille ei ole porttia). Kausitarra tulee kiinnittää näkyvälle paikalle veneeseen tai jos varasit talvi- tai säilytyspaikan, suojatelttaan, traileriin tai pukkiin.\n\nJos varasit säilytyspaikan Ämmäsmäeltä:\nÄmmäsmäen kulkulätkän noudosta tulee sopia ennakkoon soittamalla numeroon 050 3209 681 arkisin kello 9-13. Kulkulätkä noudetaan Suomenojan satamasta (Hylkeenpyytäjäntie 9) maksukuittia näyttämällä.\n\nHallinnoi varauksiasi, veneitäsi ja omia tietojasi helposti osoitteessa https://varaukset.espoo.fi/kuntalainen/omat-tiedot.\n\nVenesatamia koskevat sopimusehdot ja säännöt sekä muuta infoa löydät osoitteesta https://www.espoo.fi/fi/liikunta-ja-luonto/veneily.\n\nTerveisin\nMerelliset ulkoilupalvelut\nvenepaikat@espoo.fi'
WHERE id = 'reservation_created_by_employee';

UPDATE email_template SET subject='Vahvistus Espoon kaupungin {{placeType}}varauksesta',
                          body = E'Hyvä asiakas,\n\nSinulle on varattu espoon kaupungin {{reservationDescription}}. Lähetämme sähköpostilla lisätietoa laiturin portin avaimesta sekä kausitarran postitse. Kausitarra tulee kiinnittää näkyvälle paikalle veneeseen, tai jos varasit talvi- tai säilytyspaikan, esim. suojatelttaan, traileriin tai pukkiin.\n\nVuokralainen:\n{{reserverName}}\n\nVenepaikan nimi {{name}}\nVenepaikan leveys {{width}}\nVenepaikan pituus {{length}}\nVenepaikan varustus {{amenity}}\nVarauksesi on voimassa {{endDate}}.\n\nJos varasit laituripaikan, saat myöhemmin postissa kausitarran ja satamakartan, jossa avainkoodi laiturin portin avaimen teettämistä varten (Otsolahden F-laiturille ei ole porttia). Kausitarra tulee kiinnittää näkyvälle paikalle veneeseen tai jos varasit talvi- tai säilytyspaikan, suojatelttaan, traileriin tai pukkiin.\n\nJos varasit säilytyspaikan Ämmäsmäeltä:\nÄmmäsmäen kulkulätkän noudosta tulee sopia ennakkoon soittamalla numeroon 050 3209 681 arkisin kello 9-13. Kulkulätkä noudetaan Suomenojan satamasta (Hylkeenpyytäjäntie 9) maksukuittia näyttämällä.\n\nHallinnoi varauksiasi, veneitäsi ja omia tietojasi helposti osoitteessa https://varaukset.espoo.fi/kuntalainen/omat-tiedot.\n\nVenesatamia koskevat sopimusehdot ja säännöt sekä muuta infoa löydät osoitteesta https://www.espoo.fi/fi/liikunta-ja-luonto/veneily.\n\nTerveisin\nMerelliset ulkoilupalvelut\nvenepaikat@espoo.fi'
WHERE id = 'reservation_created_by_employee_confirmed';

UPDATE email_template SET subject='Espoon kaupungin {{placeType}}varauksen jatkaminen',
                          body = E'Hyvä asiakas,\n\nVeneelle varaamasi {{placeType}} on maksettu ja varaus on vahvistettu uudelle kaudelle.\n\nVuokralainen:\n{{reserverName}}\n\nPaikan tiedot:\nPaikan nimi: {{name}}\nPaikan leveys {{width}}\nPaikan pituus {{length}}\nPaikan varuste/säilytystapa {{amenity}}\n\nLähetämme kausitarran postitse.\n\nVarauksesi on voimassa {{endDate}}.\n\nHallinnoi varauksiasi, veneitäsi ja omia tietojasi helposti osoitteessa https://varaukset.espoo.fi/kuntalainen/omat-tiedot.\n\nVenesatamia koskevat sopimusehdot ja säännöt sekä muuta infoa löydät osoitteesta https://www.espoo.fi/fi/liikunta-ja-luonto/veneily.\n\nTerveisin\nMerelliset ulkoilupalvelut\nvenepaikat@espoo.fi'
                      WHERE id = 'reservation_renewed_by_citizen';


UPDATE email_template SET subject='Espoon kaupungin {{placeType}}varauksen jatkaminen',
                          body = E'Hyvä asiakas,\n\nVaraamasi Espoon kaupungin {{placeType}} on jatkettu uudelle kaudelle.\n\nSinulle on lähetetty lasku osoitteeseen {{invoiceAddress}}. Vahvistaaksesi varauksen, maksa paikka eräpäivään mennessä. Maksamaton paikka irtisanoutuu ja se vapautuu muiden varattavaksi.\n\nVuokralainen: {{reserverName}}\n\nVenepaikan nimi {{name}}\nVenepaikan leveys {{width}}\nVenepaikan pituus {{length}}\nVenepaikan varustus {{amenity}}\nVarauksesi on voimassa {{endDate}}.\n\nHallinnoi varauksiasi, veneitäsi ja omia tietojasi helposti osoitteessa https://varaukset.espoo.fi/kuntalainen/omat-tiedot.\n\nVenesatamia koskevat sopimusehdot ja säännöt sekä muuta infoa löydät osoitteesta https://www.espoo.fi/fi/liikunta-ja-luonto/veneily.\n\nTerveisin\nMerelliset ulkoilupalvelut\nvenepaikat@espoo.fi'
WHERE id = 'reservation_renewed_by_employee';


UPDATE email_template SET subject='Vahvistus Espoon kaupungin {{placeType}}varauksen vaihdosta',
    body = E'Hyvä asiakas,\n\nOlet vaihtanut Espoon kaupungilta vuokraamaasi {{placeType}}a.\n\nHUOM! Vanha paikka päättyy heti vaihdon yhteydessä ja vene tulee siirtää pois vanhalta paikalta, sillä vanha paikkasi on vapautunut seuraavalle vuokrattavaksi. Venepaikkasi vuokrakausi säilyy ennallaan.\n\nJos vaihdoit laituripaikkaa:\nJotta saat uuden kausitarran ja avainkoodin uutta paikkaasi varten, ota yhteyttä sähköpostilla venepaikat@espoo.fi tai puhelimitse 09 81658984 ma ja ke klo 12.30-15 ja to 9-11.\n\nUusi paikka:\n\nVuokralainen:\n{{reserverName}}\n\nPaikan tiedot:\nPaikan nimi: {{name}}\nPaikan leveys {{width}}\nPaikan pituus {{length}}\nPaikan varuste/säilytystapa {{amenity}}\n\nVarauksesi on voimassa {{endDate}}.\n\nHallinnoi varauksiasi, veneitäsi ja omia tietojasi helposti osoitteessa https://varaukset.espoo.fi/kuntalainen/omat-tiedot.\n\nVenesatamia koskevat sopimusehdot ja säännöt sekä muuta infoa löydät osoitteesta https://www.espoo.fi/fi/liikunta-ja-luonto/veneily.\n\nTerveisin\nMerelliset ulkoilupalvelut\nvenepaikat@espoo.fi'
WHERE id = 'reservation_switched_by_citizen';


UPDATE email_template SET id='reservation_termination_by_citizen',
                          subject='Vahvistus Espoon kaupungin venepaikan irtisanomisesta',
                          body=E'Hei!,\n\nPaikka {{reservationDescription}} on irtisanottu.\n\nIrtisanoaja: {{terminatorName}}\n\nPaikan vuokraaja: {{reserverName}}\n\nPaikan tulee olla tyhjä ja siivottu seuraavaa vuokralaista varten.\n\nJos irtisanoit laituri- tai traileripaikan, tulee se tyhjentää välittömästi.\nTalvi- ja Ämmäsmäen säilytyspaikan voit pitää vielä kuluvan kauden loppuun asti.\n\nJos irtisanoit Ämmäsmäen säilytyspaikan:\nÄmmäsmäen kulkulätkä tulee palauttaa Suomenojan satamaan (Hylkeenpyytäjäntie 9).\n\nMikäli et ole irtisanonut paikkaasi, ota yhteyttä sähköpostilla venepaikat@espoo.fi\n\nTerveisin,\n\nMerelliset ulkoilupalvelut\nvenepaikat@espoo.fi'
WHERE id='reservation_termination_notice_no_refund';


UPDATE email_template SET id='reservation_termination_by_citizen_to_employee',
                          subject='Paikka {{reservationDescription}} irtisanottu, asiakas: {{reserverName}}',
                          body=E'Hei!,\n\nPaikka {{reservationDescription}} on irtisanottu {{time}}\n\nPaikan vuokraaja: {{reserverName}}\nSähköposti:{{reserverEmail}}\n\nIrtisanoaja:\nNimi: {{terminatorName}}\nSähköposti: {{terminatorEmail}}\nPuhelinnumero:{{terminatorPhone}}'
                          WHERE id='marine_reservation_termination_employee_notice'