# SPDX-FileCopyrightText: 2023-2024 City of Espoo
#
# SPDX-License-Identifier: LGPL-2.1-or-later

spring:
  main:
    banner-mode: "off"
  application:
    name: "oppivelvollisuus-service"
  datasource:
    driver-class-name: "org.postgresql.Driver"
    type: "com.zaxxer.hikari.HikariDataSource"
    hikari:
      data-source-properties:
        socketTimeout: 30000
  sql:
    init:
      continue-on-error: false
      encoding: "UTF-8"
