services:
  frontend:
    image: 730335326824.dkr.ecr.eu-north-1.amazonaws.com/vekkuli/frontend:${TAG:-master}
    build:
      context: ../frontend/
    ports:
      - "9000:80"
    environment:
      RESOLVER: "127.0.0.11 ipv6=off"
      API_GATEWAY_URL: http://api-gateway:3000
      RATE_LIMIT_CIDR_WHITELIST: "0.0.0.0/0;::/0"
      HTTP_SCHEME: http
    depends_on:
      - api-gateway

  api-gateway:
    image: 730335326824.dkr.ecr.eu-north-1.amazonaws.com/vekkuli/api-gateway:${TAG:-master}
    build:
      context: ../api-gateway/
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: local
      HTTP_PORT: 3000
      SERVICE_URL: http://service-e2e-tests:8080
      JWT_KID: "vekkuli-api-gateway"
      JWT_PRIVATE_KEY: "config/test-cert/jwt_private_key.pem"
      AD_MOCK: "true"
      DEV_LOGIN: "true"
      COOKIE_SECRET: cookie_secret
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DISABLE_SECURITY: "true"
    depends_on:
      - redis

  service-e2e-tests:
    image: ghcr.io/espoon-voltti/vekkuli/service-builder:${TAG:-master}
    build:
      context: ../service/
      target: builder
    ports:
      - "8080:8080"
    volumes:
      - ./service-build:/app/build
    environment:
      JAVA_OPTS: -server -Djava.security.egd=file:/dev/./urandom -Xms1024m -Xss512k -Xmx1024m -XX:TieredStopAtLevel=1
      SPRING_DATASOURCE_URL: jdbc:postgresql://vekkuli-db:5432/vekkuli
      SPRING_DATASOURCE_USERNAME: vekkuli
      SPRING_DATASOURCE_PASSWORD: postgres
      ENVIRONMENT: local-docker
    entrypoint: ./e2e-test-entrypoint.sh
    depends_on:
      - vekkuli-db
      - api-gateway
      - frontend
      - redis
