version: '3.5'

services:
  service-tests:
    image: 730335326824.dkr.ecr.eu-north-1.amazonaws.com/vekkuli/service-builder:${TAG:-master}
    build:
      context: ../service/
      target: builder
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: -server -Djava.security.egd=file:/dev/./urandom -Xms1024m -Xss512k -Xmx1024m -XX:TieredStopAtLevel=1
      SPRING_DATASOURCE_URL: jdbc:postgresql://vekkuli-db:5432/vekkuli
    entrypoint: ./gradlew test
    depends_on:
      - vekkuli-db
