# SPDX-FileCopyrightText: 2023-2024 City of Espoo
#
# SPDX-License-Identifier: LGPL-2.1-or-later

version: '3.5'

services:
  frontend:
    image: 095341522062.dkr.ecr.eu-north-1.amazonaws.com/oppivelvollisuus/frontend:${TAG:-master}
    build:
      context: ../frontend/
    ports:
      - "9000:80"
    environment:
      RESOLVER: "127.0.0.11 ipv6=off"
      API_GATEWAY_URL: http://api-gateway:3000
      HTTP_SCHEME: http
    depends_on:
      - api-gateway

  api-gateway:
    image: 095341522062.dkr.ecr.eu-north-1.amazonaws.com/oppivelvollisuus/api-gateway:${TAG:-master}
    build:
      context: ../api-gateway/
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: local
      HTTP_PORT: 3000
      SERVICE_URL: http://service-e2e-tests:8080
      JWT_KID: "oppivelvollisuus-api-gateway"
      JWT_PRIVATE_KEY: "config/test-cert/jwt_private_key.pem"
      AD_MOCK: "true"
      DEV_LOGIN: "true"
      COOKIE_SECRET: cookie_secret
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DISABLE_SECURITY: "true"
    depends_on:
      - redis

  service-e2e-tests:
    image: 095341522062.dkr.ecr.eu-north-1.amazonaws.com/oppivelvollisuus/service-builder:${TAG:-master}
    build:
      context: ../service/
      target: builder
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: -server -Djava.security.egd=file:/dev/./urandom -Xms1024m -Xss512k -Xmx1024m -XX:TieredStopAtLevel=1
      SPRING_DATASOURCE_URL: jdbc:postgresql://oppivelvollisuus-db:5432/oppivelvollisuus
      SPRING_DATASOURCE_USERNAME: oppivelvollisuus
      SPRING_DATASOURCE_PASSWORD: postgres
      E2E_ENV: docker
    entrypoint: ./e2e-test-entrypoint.sh
    depends_on:
      - oppivelvollisuus-db
