version: '3.5'

services:
  vekkuli-db:
    image: postgres:16.9-alpine3.21
    ports:
      - "5432:5432"
    volumes:
      - vekkuli-db-data:/var/lib/postgresql/data
      - ./db/test-db.sh:/docker-entrypoint-initdb.d/test-db.sh
    environment:
      POSTGRES_DB: vekkuli
      POSTGRES_USER: vekkuli
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: '[ "$$(redis-cli -h 127.0.0.1 ping)" == "PONG" ]'
      interval: 1s
      timeout: 5s
      retries: 5

volumes:
  vekkuli-db-data:
    driver: local
