#!/bin/bash

set -euo pipefail

COMPOSE="${COMPOSE:-docker compose}"

if [ "${BUILD:-true}" = "true" ] && ( [ "$1" = "up" ] || [ "$1" = "run" ] ); then
    $COMPOSE -f docker-compose.yml -f docker-compose.e2e.yml build --parallel
fi

$COMPOSE -f docker-compose.yml -f docker-compose.e2e.yml $@
