name: Cleanup
on:
  schedule:
    - cron: '0 2 * * *' # every night at 02:00

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Cleanup cached images
        uses: actions/delete-package-versions@v5
        with:
          package-name: vekkuli/service-builder
          package-type: container
          min-versions-to-keep: 0
